/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CitySlugRouteImport } from './routes/$citySlug'
import { Route as IndexRouteImport } from './routes/index'

const CitySlugRoute = CitySlugRouteImport.update({
  id: '/$citySlug',
  path: '/$citySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$citySlug': typeof CitySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$citySlug': typeof CitySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$citySlug': typeof CitySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$citySlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$citySlug'
  id: '__root__' | '/' | '/$citySlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CitySlugRoute: typeof CitySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$citySlug': {
      id: '/$citySlug'
      path: '/$citySlug'
      fullPath: '/$citySlug'
      preLoaderRoute: typeof CitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CitySlugRoute: CitySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
